#!/usr/bin/env bash
# Install weekly cron for docker-disk-prune.sh on the host (srv03).
#
# Usage (on VPS as root or with sudo):
#   cd /opt/24alert
#   sudo bash scripts/install-docker-prune-cron.sh
#
# Schedule: Sunday 04:30 UTC (07:30 MSK winter / 08:30 MSK summer)
# Override: CRON_SCHEDULE='0 3 * * 0' sudo bash scripts/install-docker-prune-cron.sh

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PRUNE_SCRIPT="$REPO_ROOT/scripts/docker-disk-prune.sh"
CRON_FILE="/etc/cron.d/24alert-docker-prune"
CRON_SCHEDULE="${CRON_SCHEDULE:-30 4 * * 0}"

if [ ! -f "$PRUNE_SCRIPT" ]; then
  echo "Missing $PRUNE_SCRIPT"
  exit 1
fi
chmod +x "$PRUNE_SCRIPT"

if [ "$(id -u)" -ne 0 ]; then
  echo "Run as root: sudo bash $0"
  exit 1
fi

touch /var/log/24alert-docker-prune.log
chmod 644 /var/log/24alert-docker-prune.log

cat >"$CRON_FILE" <<EOF
# 24alert: weekly Docker image cleanup (generated by install-docker-prune-cron.sh)
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
$CRON_SCHEDULE root $PRUNE_SCRIPT >> /var/log/24alert-docker-prune.log 2>&1
EOF
chmod 644 "$CRON_FILE"

echo "Installed $CRON_FILE"
echo "Schedule: $CRON_SCHEDULE"
cat "$CRON_FILE"
echo ""
echo "Test now: sudo bash $PRUNE_SCRIPT --verbose"
echo "Log: /var/log/24alert-docker-prune.log"
